"""Generated built-in Defold preference metadata. Do not edit manually."""

CATALOG = ({'name': 'ASSET_BROWSER',
  'path': 'asset-browser',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for asset browser.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'ASSET_BROWSER_TRACK_ACTIVE_TAB',
  'path': 'asset-browser/track-active-tab',
  'type': 'boolean',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for asset browser track active tab.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'INPUT',
  'path': 'input',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for input.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'INPUT_KEYMAP_PATH',
  'path': 'input/keymap-path',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for input keymap path.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE',
  'path': 'code',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for code.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_CUSTOM_EDITOR',
  'path': 'code/custom-editor',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code custom editor.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_OPEN_FILE',
  'path': 'code/open-file',
  'type': 'string',
  'scope': 'global',
  'default': '{file}',
  'has_default': True,
  'description': 'Built-in Defold editor preference for code open file.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_OPEN_FILE_AT_LINE',
  'path': 'code/open-file-at-line',
  'type': 'string',
  'scope': 'global',
  'default': '{file}:{line}',
  'has_default': True,
  'description': 'Built-in Defold editor preference for code open file at line.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_ZOOM_ON_SCROLL',
  'path': 'code/zoom-on-scroll',
  'type': 'boolean',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code zoom on scroll.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_HOVER',
  'path': 'code/hover',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for code hover.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FONT',
  'path': 'code/font',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for code font.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FONT_NAME',
  'path': 'code/font/name',
  'type': 'string',
  'scope': 'global',
  'default': 'Dejavu Sans Mono',
  'has_default': True,
  'description': 'Font family used by the code editor.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FONT_SIZE',
  'path': 'code/font/size',
  'type': 'number',
  'scope': 'global',
  'default': 12.0,
  'has_default': True,
  'description': 'Font size used by the code editor.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FIND',
  'path': 'code/find',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for code find.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FIND_TERM',
  'path': 'code/find/term',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code find term.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FIND_REPLACEMENT',
  'path': 'code/find/replacement',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code find replacement.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FIND_WHOLE_WORD',
  'path': 'code/find/whole-word',
  'type': 'boolean',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code find whole word.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FIND_CASE_SENSITIVE',
  'path': 'code/find/case-sensitive',
  'type': 'boolean',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code find case sensitive.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_FIND_WRAP',
  'path': 'code/find/wrap',
  'type': 'boolean',
  'scope': 'project',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for code find wrap.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_BREAKPOINTS',
  'path': 'code/breakpoints',
  'type': 'array',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for code breakpoints.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_AUTO_CLOSING_PARENS',
  'path': 'code/auto-closing-parens',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Whether the code editor automatically inserts matching parentheses.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_VISIBILITY',
  'path': 'code/visibility',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for code visibility.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_VISIBILITY_INDENTATION_GUIDES',
  'path': 'code/visibility/indentation-guides',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for code visibility indentation guides.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_VISIBILITY_MINIMAP',
  'path': 'code/visibility/minimap',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for code visibility minimap.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CODE_VISIBILITY_WHITESPACE',
  'path': 'code/visibility/whitespace',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for code visibility whitespace.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'TOOLS',
  'path': 'tools',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for tools.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'TOOLS_ADB_PATH',
  'path': 'tools/adb-path',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for tools adb path.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'TOOLS_IOS_DEPLOY_PATH',
  'path': 'tools/ios-deploy-path',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for tools ios deploy path.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'EXTENSIONS',
  'path': 'extensions',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for extensions.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'EXTENSIONS_BUILD_SERVER',
  'path': 'extensions/build-server',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for extensions build server.',
  'group': False,
  'enum_values': None,
  'ui': {'prompt': ['connection-properties/defold-build-server-url']}},
 {'name': 'EXTENSIONS_BUILD_SERVER_USERNAME',
  'path': 'extensions/build-server-username',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for extensions build server username.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'EXTENSIONS_BUILD_SERVER_PASSWORD',
  'path': 'extensions/build-server-password',
  'type': 'password',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for extensions build server password.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'EXTENSIONS_BUILD_SERVER_HEADERS',
  'path': 'extensions/build-server-headers',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for extensions build server headers.',
  'group': False,
  'enum_values': None,
  'ui': {'multiline': True}},
 {'name': 'SEARCH_IN_FILES',
  'path': 'search-in-files',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for search in files.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'SEARCH_IN_FILES_TERM',
  'path': 'search-in-files/term',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for search in files term.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SEARCH_IN_FILES_EXTS',
  'path': 'search-in-files/exts',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for search in files exts.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SEARCH_IN_FILES_INCLUDE_LIBRARIES',
  'path': 'search-in-files/include-libraries',
  'type': 'boolean',
  'scope': 'project',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for search in files include libraries.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'OPEN_ASSETS',
  'path': 'open-assets',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for open assets.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'OPEN_ASSETS_TERM',
  'path': 'open-assets/term',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for open assets term.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'BUILD',
  'path': 'build',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for build.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'BUILD_LINT_CODE',
  'path': 'build/lint-code',
  'type': 'boolean',
  'scope': 'project',
  'default': True,
  'has_default': True,
  'description': 'Whether project builds run the configured code lint checks.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'BUILD_TEXTURE_COMPRESSION',
  'path': 'build/texture-compression',
  'type': 'boolean',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Whether builds use texture compression.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'BUILD_OPEN_HTML5_BUILD',
  'path': 'build/open-html5-build',
  'type': 'boolean',
  'scope': 'project',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for build open html5 build.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'BUNDLE',
  'path': 'bundle',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for bundle.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'BUNDLE_LAST_BUNDLE_COMMAND',
  'path': 'bundle/last-bundle-command',
  'type': 'one-of',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for bundle last bundle command.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'BUNDLE_OUTPUT_DIRECTORY',
  'path': 'bundle/output-directory',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for bundle output directory.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'BUNDLE_OPEN_OUTPUT_DIRECTORY',
  'path': 'bundle/open-output-directory',
  'type': 'boolean',
  'scope': 'project',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for bundle open output directory.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW',
  'path': 'window',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for window.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW_DIMENSIONS',
  'path': 'window/dimensions',
  'type': 'one-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for window dimensions.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW_SPLIT_POSITIONS',
  'path': 'window/split-positions',
  'type': 'object-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for window split positions.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW_HIDDEN_PANES',
  'path': 'window/hidden-panes',
  'type': 'set',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for window hidden panes.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW_LOCALE',
  'path': 'window/locale',
  'type': 'locale',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for window locale.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW_KEYMAP',
  'path': 'window/keymap',
  'type': 'object-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for window keymap.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WINDOW_MOUSE_BINDINGS',
  'path': 'window/mouse-bindings',
  'type': 'object-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for window mouse bindings.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW',
  'path': 'workflow',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for workflow.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_LOAD_EXTERNAL_CHANGES_ON_APP_FOCUS',
  'path': 'workflow/load-external-changes-on-app-focus',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for workflow load external changes on app focus.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_SAVE_ON_APP_FOCUS_LOST',
  'path': 'workflow/save-on-app-focus-lost',
  'type': 'boolean',
  'scope': 'global',
  'default': False,
  'has_default': True,
  'description': 'Built-in Defold editor preference for workflow save on app focus lost.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_RECENT_FILES',
  'path': 'workflow/recent-files',
  'type': 'array',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for workflow recent files.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_LAST_SELECTED_TABS',
  'path': 'workflow/last-selected-tabs',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for workflow last selected tabs.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_LAST_SELECTED_TABS_SELECTED_PANE',
  'path': 'workflow/last-selected-tabs/selected-pane',
  'type': 'integer',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for workflow last selected tabs selected pane.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_LAST_SELECTED_TABS_TAB_SELECTION_BY_PANE',
  'path': 'workflow/last-selected-tabs/tab-selection-by-pane',
  'type': 'array',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for workflow last selected tabs tab selection by pane.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_OPEN_TABS',
  'path': 'workflow/open-tabs',
  'type': 'array',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for workflow open tabs.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WORKFLOW_SAVED_COLORS',
  'path': 'workflow/saved-colors',
  'type': 'array',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for workflow saved colors.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CONSOLE',
  'path': 'console',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for console.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'CONSOLE_FILTERING',
  'path': 'console/filtering',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for console filtering.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'CONSOLE_FILTERS',
  'path': 'console/filters',
  'type': 'array',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for console filters.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN',
  'path': 'run',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for run.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_INSTANCE_COUNT',
  'path': 'run/instance-count',
  'type': 'integer',
  'scope': 'project',
  'default': 1,
  'has_default': True,
  'description': 'Number of local engine instances launched by Build and Run.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_SELECTED_TARGET_ID',
  'path': 'run/selected-target-id',
  'type': 'one-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for run selected target id.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_MANUAL_TARGET_IP_PORT',
  'path': 'run/manual-target-ip+port',
  'type': 'string',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for run manual target ip and port.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_QUIT_ON_ESCAPE',
  'path': 'run/quit-on-escape',
  'type': 'boolean',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for run quit on escape.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_SIMULATE_ROTATED_DEVICE',
  'path': 'run/simulate-rotated-device',
  'type': 'boolean',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for run simulate rotated device.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_SIMULATED_RESOLUTION',
  'path': 'run/simulated-resolution',
  'type': 'one-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for run simulated resolution.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'RUN_ENGINE_ARGUMENTS',
  'path': 'run/engine-arguments',
  'type': 'string',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Command-line arguments supplied to locally launched engines.',
  'group': False,
  'enum_values': None,
  'ui': {'multiline': True}},
 {'name': 'SCENE',
  'path': 'scene',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for scene.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_MOVE_WHOLE_PIXELS',
  'path': 'scene/move-whole-pixels',
  'type': 'boolean',
  'scope': 'global',
  'default': True,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene move whole pixels.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID',
  'path': 'scene/grid',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for scene grid.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID_SIZE',
  'path': 'scene/grid/size',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for scene grid size.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID_SIZE_X',
  'path': 'scene/grid/size/x',
  'type': 'number',
  'scope': 'project',
  'default': 1.0,
  'has_default': True,
  'description': 'Scene editor grid spacing on the X axis.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID_SIZE_Y',
  'path': 'scene/grid/size/y',
  'type': 'number',
  'scope': 'project',
  'default': 1.0,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene grid size y.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID_SIZE_Z',
  'path': 'scene/grid/size/z',
  'type': 'number',
  'scope': 'project',
  'default': 1.0,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene grid size z.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID_ACTIVE_PLANE',
  'path': 'scene/grid/active-plane',
  'type': 'enum',
  'scope': 'project',
  'default': 'z',
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene grid active plane.',
  'group': False,
  'enum_values': ['x', 'y', 'z'],
  'ui': None},
 {'name': 'SCENE_GRID_OPACITY',
  'path': 'scene/grid/opacity',
  'type': 'number',
  'scope': 'project',
  'default': 0.25,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene grid opacity.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_GRID_COLOR',
  'path': 'scene/grid/color',
  'type': 'tuple',
  'scope': 'project',
  'default': [0.5, 0.5, 0.5, 1.0],
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene grid color.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_PERSPECTIVE_CAMERA',
  'path': 'scene/perspective-camera',
  'type': 'object',
  'scope': 'project',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for scene perspective camera.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_PERSPECTIVE_CAMERA_SPEED',
  'path': 'scene/perspective-camera/speed',
  'type': 'number',
  'scope': 'project',
  'default': 1.0,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene perspective camera speed.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_PERSPECTIVE_CAMERA_LOOK_SENSITIVITY',
  'path': 'scene/perspective-camera/look-sensitivity',
  'type': 'number',
  'scope': 'project',
  'default': 0.145,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene perspective camera look sensitivity.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_PERSPECTIVE_CAMERA_INVERT_Y',
  'path': 'scene/perspective-camera/invert-y',
  'type': 'boolean',
  'scope': 'project',
  'default': False,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene perspective camera invert y.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_PERSPECTIVE_CAMERA_FOV',
  'path': 'scene/perspective-camera/fov',
  'type': 'number',
  'scope': 'project',
  'default': 37.8,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene perspective camera fov.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'SCENE_PERSPECTIVE_CAMERA_WALKING_MODE',
  'path': 'scene/perspective-camera/walking-mode',
  'type': 'boolean',
  'scope': 'project',
  'default': False,
  'has_default': True,
  'description': 'Built-in Defold editor preference for scene perspective camera walking mode.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'DEV',
  'path': 'dev',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for dev.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'DEV_CUSTOM_ENGINE',
  'path': 'dev/custom-engine',
  'type': 'one-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for dev custom engine.',
  'group': False,
  'enum_values': None,
  'ui': {'type': 'string'}},
 {'name': 'WELCOME',
  'path': 'welcome',
  'type': 'object',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference group for welcome.',
  'group': True,
  'enum_values': None,
  'ui': None},
 {'name': 'WELCOME_LAST_OPENED_PROJECT_DIRECTORY',
  'path': 'welcome/last-opened-project-directory',
  'type': 'one-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for welcome last opened project directory.',
  'group': False,
  'enum_values': None,
  'ui': None},
 {'name': 'WELCOME_RECENT_PROJECTS',
  'path': 'welcome/recent-projects',
  'type': 'object-of',
  'scope': 'global',
  'default': None,
  'has_default': False,
  'description': 'Built-in Defold editor preference for welcome recent projects.',
  'group': False,
  'enum_values': None,
  'ui': None})
