-- Atlas data from resource.get_atlas()
return {
  texture = "/_generated_f679ccf0.texturec",
  animations = {
    [1] = {
      flip_vertical = false,
      width = 53,
      height = 49,
      playback = 0,
      id = "Squirrel_1",
      fps = 30,
      frame_start = 1,
      frame_end = 2,
      flip_horizontal = false,
    },
    [2] = {
      flip_vertical = false,
      width = 95,
      height = 87,
      playback = 0,
      id = "Squirrel_2",
      fps = 30,
      frame_start = 2,
      frame_end = 3,
      flip_horizontal = false,
    },
    [3] = {
      flip_vertical = false,
      width = 30,
      height = 28,
      playback = 0,
      id = "Squirrel_3",
      fps = 30,
      frame_start = 3,
      frame_end = 4,
      flip_horizontal = false,
    },
    [4] = {
      flip_vertical = false,
      width = 39,
      height = 36,
      playback = 0,
      id = "Squirrel_4",
      fps = 30,
      frame_start = 4,
      frame_end = 5,
      flip_horizontal = false,
    },
    [5] = {
      flip_vertical = false,
      width = 56,
      height = 51,
      playback = 0,
      id = "Squirrel_5",
      fps = 30,
      frame_start = 5,
      frame_end = 6,
      flip_horizontal = false,
    },
    [6] = {
      flip_vertical = false,
      width = 25,
      height = 22,
      playback = 0,
      id = "Squirrel_6",
      fps = 30,
      frame_start = 6,
      frame_end = 7,
      flip_horizontal = false,
    },
    [7] = {
      flip_vertical = false,
      width = 8,
      height = 6,
      playback = 0,
      id = "Squirrel_7",
      fps = 30,
      frame_start = 7,
      frame_end = 8,
      flip_horizontal = false,
    },
  },
  geometries = {
    [1] = {
      pivot_x = 0.5,
      width = 53,
      rotated = false,
      height = 49,
      uvs = {
        [1] = 161,
        [2] = 51,
        [3] = 161,
        [4] = 2,
        [5] = 214,
        [6] = 2,
        [7] = 214,
        [8] = 51,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 49,
        [3] = 0,
        [4] = 0,
        [5] = 53,
        [6] = 0,
        [7] = 53,
        [8] = 49,
      },
      pivot_y = 0.5,
    },
    [2] = {
      pivot_x = 0.5,
      width = 95,
      rotated = false,
      height = 87,
      uvs = {
        [1] = 2,
        [2] = 89,
        [3] = 2,
        [4] = 2,
        [5] = 97,
        [6] = 2,
        [7] = 97,
        [8] = 89,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 87,
        [3] = 0,
        [4] = 0,
        [5] = 95,
        [6] = 0,
        [7] = 95,
        [8] = 87,
      },
      pivot_y = 0.5,
    },
    [3] = {
      pivot_x = 0.5,
      width = 30,
      rotated = false,
      height = 28,
      uvs = {
        [1] = 2,
        [2] = 121,
        [3] = 2,
        [4] = 93,
        [5] = 32,
        [6] = 93,
        [7] = 32,
        [8] = 121,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 28,
        [3] = 0,
        [4] = 0,
        [5] = 30,
        [6] = 0,
        [7] = 30,
        [8] = 28,
      },
      pivot_y = 0.5,
    },
    [4] = {
      pivot_x = 0.5,
      width = 39,
      rotated = true,
      height = 36,
      uvs = {
        [1] = 218,
        [2] = 2,
        [3] = 254,
        [4] = 2,
        [5] = 254,
        [6] = 41,
        [7] = 218,
        [8] = 41,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 36,
        [3] = 0,
        [4] = 0,
        [5] = 39,
        [6] = 0,
        [7] = 39,
        [8] = 36,
      },
      pivot_y = 0.5,
    },
    [5] = {
      pivot_x = 0.5,
      width = 56,
      rotated = false,
      height = 51,
      uvs = {
        [1] = 101,
        [2] = 53,
        [3] = 101,
        [4] = 2,
        [5] = 157,
        [6] = 2,
        [7] = 157,
        [8] = 53,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 51,
        [3] = 0,
        [4] = 0,
        [5] = 56,
        [6] = 0,
        [7] = 56,
        [8] = 51,
      },
      pivot_y = 0.5,
    },
    [6] = {
      pivot_x = 0.5,
      width = 25,
      rotated = false,
      height = 22,
      uvs = {
        [1] = 101,
        [2] = 79,
        [3] = 101,
        [4] = 57,
        [5] = 126,
        [6] = 57,
        [7] = 126,
        [8] = 79,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 22,
        [3] = 0,
        [4] = 0,
        [5] = 25,
        [6] = 0,
        [7] = 25,
        [8] = 22,
      },
      pivot_y = 0.5,
    },
    [7] = {
      pivot_x = 0.5,
      width = 8,
      rotated = false,
      height = 6,
      uvs = {
        [1] = 218,
        [2] = 51,
        [3] = 218,
        [4] = 45,
        [5] = 226,
        [6] = 45,
        [7] = 226,
        [8] = 51,
      },
      indices = {
        [1] = 0,
        [2] = 1,
        [3] = 2,
        [4] = 0,
        [5] = 2,
        [6] = 3,
      },
      vertices = {
        [1] = 0,
        [2] = 6,
        [3] = 0,
        [4] = 0,
        [5] = 8,
        [6] = 0,
        [7] = 8,
        [8] = 6,
      },
      pivot_y = 0.5,
    },
  },
}
