name: Add new issues to backlog
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add_to_backlog:
    runs-on: ubuntu-latest
    permissions:
      project: read
    steps:
      - run: gh project item-add "$PROJECT_ID" --owner "$OWNER" --url "$ISSUE_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          OWNER: defold
          ISSUE_URL: ${{ github.event.issue.html_url }}
          PROJECT_ID: 102
