name: Add new issues to backlog
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add_to_backlog:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      projects: write
    steps:
      - run: gh issue edit "$NUMBER" --add-project "$PROJECT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          PROJECT: Defold backlog
