name: Build with bob

on: [push, pull_request]

env:
  VERSION_FILENAME: 'info.json'
  BUILD_SERVER: 'https://build-stage.defold.com'
  CHANNEL: 'alpha'
  PLUGIN_SO: './defold-spine/plugins/lib/x86_64-linux/libSpineExt.so'

jobs:
  build_with_bob:
    strategy:
      matrix:
        platform: [armv7-android, x86_64-linux, js-web]
    runs-on: ubuntu-latest

    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21.0.5+11.0.LTS'
          architecture: x64
          distribution: 'temurin'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libopenal-dev freeglut3-dev libgl-dev libglx-dev libegl-dev

      - name: Get Defold version
        run: |
          TMPVAR=`curl -s http://d.defold.com/${{env.CHANNEL}}/${{env.VERSION_FILENAME}} | jq -r '.sha1'`
          echo "DEFOLD_VERSION=${TMPVAR}" >> $GITHUB_ENV
          echo "Found version ${TMPVAR}"

      - name: Download bob.jar
        run: |
          wget -q http://d.defold.com/archive/${{env.CHANNEL}}/${{env.DEFOLD_VERSION}}/bob/bob.jar
          java -jar bob.jar --version

      - name: Check shared dependencies
        run: |
          ldd ${PLUGIN_SO}
          if ldd ${PLUGIN_SO} | grep -e 'not found' ; then (exit 1); fi

      - name: Resolve libraries
        run: java -jar bob.jar resolve --email a@b.com --auth 123456
      - name: Build Tools
        run: SERVER=${{env.BUILD_SERVER}} DEFOLDSDK=${{env.DEFOLD_VERSION}} BOB=./bob.jar ./utils/build_plugins.sh x86_64-linux
      - name: Build
        run: java -jar bob.jar --platform=${{ matrix.platform }} build --archive --build-server=${{env.BUILD_SERVER}} --defoldsdk=${{env.DEFOLD_VERSION}}
      - name: Bundle
        run: java -jar bob.jar --platform=${{ matrix.platform }} bundle

  build_with_bob_windows:
    strategy:
      matrix:
        platform: [x86_64-win32, x86-win32]
    runs-on: windows-latest

    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21.0.5+11.0.LTS'
          architecture: x64
          distribution: 'temurin'

      - name: Get Defold version
        run: |
          TMPVAR=`curl -s http://d.defold.com/${{env.CHANNEL}}/${{env.VERSION_FILENAME}} | jq -r '.sha1'`
          echo "DEFOLD_VERSION=${TMPVAR}" >> $GITHUB_ENV
          echo "Found version ${TMPVAR}"
        shell: bash

      - name: Download bob.jar
        run: |
          curl -s -o bob.jar http://d.defold.com/archive/${{env.CHANNEL}}/${{env.DEFOLD_VERSION}}/bob/bob.jar
          java -jar bob.jar --version

      - name: Resolve libraries
        run: java -jar bob.jar resolve --email a@b.com --auth 123456

      - name: Build Tools
        run: |
          set SERVER=${{env.BUILD_SERVER}}
          set DEFOLDSDK=${{env.DEFOLD_VERSION}}
          set BOB=./bob.jar
          ./utils/build_plugins.sh x86_64-win32

      - name: Build
        run: java -jar bob.jar --platform=${{ matrix.platform }} build --archive --build-server=${{env.BUILD_SERVER}} --defoldsdk=${{env.DEFOLD_VERSION}}

      - name: Bundle
        run: java -jar bob.jar --platform=${{ matrix.platform }} bundle

  # macOS is not technically needed for building, but we want to test bundling as well, since we're also testing the manifest merging
  build_with_bob_macos:
    strategy:
      matrix:
        platform: [arm64-ios, x86_64-macos, arm64-macos]
    runs-on: macOS-latest

    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21.0.5+11.0.LTS'
          architecture: x64
          distribution: 'temurin'

      - name: Get Defold version
        run: |
          TMPVAR=`curl -s http://d.defold.com/${{env.CHANNEL}}/${{env.VERSION_FILENAME}} | jq -r '.sha1'`
          echo "DEFOLD_VERSION=${TMPVAR}" >> $GITHUB_ENV
          echo "Found version ${TMPVAR}"

      - name: Install dependencies
        run: |
          brew install tree

      - name: Download bob.jar
        run: |
          wget -q http://d.defold.com/archive/${{env.CHANNEL}}/${{env.DEFOLD_VERSION}}/bob/bob.jar
          java -jar bob.jar --version

      - name: Resolve libraries
        run: java -jar bob.jar resolve --email a@b.com --auth 123456
      - name: Build Tools
        run: SERVER=${{env.BUILD_SERVER}} DEFOLDSDK=${{env.DEFOLD_VERSION}} BOB=./bob.jar ./utils/build_plugins.sh x86_64-macos
      - name: Build
        run: java -jar bob.jar --platform=${{ matrix.platform }} build --archive --build-server=${{env.BUILD_SERVER}} --defoldsdk=${{env.DEFOLD_VERSION}}
      - name: Bundle
        run: java -jar bob.jar --platform=${{ matrix.platform }} bundle
